//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using Portal.Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortalDBEntities : DbContext
    {
        public PortalDBEntities()
            : base("name=PortalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CourseListTable> CourseListTables { get; set; }
        public virtual DbSet<LecturerTable> LecturerTables { get; set; }
        public virtual DbSet<StudentCourseListTable> StudentCourseListTables { get; set; }
        public virtual DbSet<StudentTable> StudentTables { get; set; }
    }
}
