//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectedCoursesTable
    {
        public string CourseId { get; set; }
        public string CourseTitle { get; set; }
        public Nullable<int> CreditHours { get; set; }
        public Nullable<int> LevelTaken { get; set; }
        public string Lecturer { get; set; }
        public string Programme { get; set; }
        public string MatricNo { get; set; }
        public int No { get; set; }
        public Nullable<int> SemesterNo { get; set; }
    }
}
