//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourseListTable
    {
        public string MatricNo { get; set; }
        public string Programme { get; set; }
        public Nullable<int> StudyLevel { get; set; }
        public string CourseId_1 { get; set; }
        public string CourseId_2 { get; set; }
        public string CourseId_3 { get; set; }
        public string CourseId_4 { get; set; }
        public string CourseId_5 { get; set; }
        public string CourseId_6 { get; set; }
        public string CourseId_7 { get; set; }
        public string CourseId_8 { get; set; }
    }
}
