//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StudentTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentTable()
        {
            this.SemesterGPA = 0.0m;
            this.CourseFormSubmit = false;
        }

        
        public int RegNo { get; set; }
        [Required(ErrorMessage = "Enter Firstname")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Enter Lastname")]
        public string LastName { get; set; }
        [Required]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Enter Department")]
        public string Department { get; set; }
        [Required(ErrorMessage = "Enter Programme")]
        public string Programme { get; set; }
        [Required(ErrorMessage = "Choose Study Level")]
        public Nullable<int> StudyLevel { get; set; }
        [Required]
        [Phone(ErrorMessage = "Enter valid phone number")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Enter valid password")]
        [RegularExpression("^(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$", ErrorMessage = "Enter valid password")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Choose Sex")]
        public string Sex { get; set; }
        [Required(ErrorMessage = "Choose Marital Status")]
        public string MaritalStatus { get; set; }
        [Required(ErrorMessage = "Enter Nationality")]
        public string Nationality { get; set; }
        [Required(ErrorMessage = "Enter Matric number")]
        public string MatricNo { get; set; }
        [Required(ErrorMessage = "Enter Date of Birth")]
        public string DateOfBirth { get; set; }
        [Required]
        [RegularExpression("^(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$")]
        public string ConfirmPassword { get; set; }
        public Nullable<decimal> SemesterGPA { get; set; }
        public Nullable<bool> CourseFormSubmit { get; set; }
    }
}

